language: node_js
node_js:
    - "node"
    - "0.10"

addons:
    code_climate:
        repo_token: ebfd01cd03917e31312870a50a83032228562857300b04f8d1200a61c88b0f0e

after_success:
    - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then node node_modules/istanbul/lib/cli.js cover test/test.js && node node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info; fi
